# Site settings
title: Daniel Pellatt
url: "https://danielpellatt.github.io" # the base hostname & protocol for your site
description: |+
  I am a Ph.D. candidate in Economics at the University of California, San Diego. My field of research is econometrics. I am available for interviews on the 2022-2023 job market.

theme: jekyll-theme-minimal


github:
  is_user_page: false

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
powered_by: false
