# Site settings
name: Daniel Pellatt
title: null
baseurl: "danielpellatt.github.io  " # the subpath of your site, e.g. /blog/
url: "https://danielpellatt.github.io" # the base hostname & protocol for your site
github_username:  danielpellatt

theme: tactile

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
