# Site settings
title: Daniel Pellatt
url: "https://danielpellatt.github.io" # the base hostname & protocol for your site
logo: headshot.jpeg
description: 
  "email: dpellatt@ucsd.edu"

theme: jekyll-theme-minimal


github:
  is_user_page: false

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
powered_by: false
