# Site settings
title: Daniel Pellatt
url: "https://danielpellatt.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
powered_by: false
