# Site settings
name: Daniel Pellatt
title: null
baseurl: "danielpellatt.github.io  " # the subpath of your site, e.g. /blog/
url: "https://danielpellatt.github.io" # the base hostname & protocol for your site
github_username:  danielpellatt

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
